version: '2'
services:
    nginx:
        build: docker/nginx/
        ports:
         - "443:443"
        volumes:
            - ./docker/nginx/site:/usr/share/nginx/html:ro
            - ./docker/nginx/certs:/etc/nginx/ssl
        links:
         - flask
    flask:
        build: docker/flask
        ports:
         - "8081:80"
        volumes:
            - ./docker/flask:/workspace
