version: '2'
services:
    nginx:
        build: docker/nginx/
        ports:
         - "80:80"
        volumes:
            - ./docker/nginx/site:/usr/share/nginx/html:ro
        links:
         - flask
         - forum
    flask:
        build: docker/flask
        ports:
         - "8081:80"
        volumes:
            - ./docker/flask:/workspace
    forum:
        build: docker/phpbb
        ports:
         - "8082:80"
        volumes:
            - ./docker/phpbb/forum:/var/www/html
        links:
            - db:mysql
    db:
        image: mariadb:latest
        ports:
         - "3306:3306"
        environment:
         - MYSQL_ROOT_PASSWORD=rootpass
         - MYSQL_DATABASE=testdb
         - MYSQL_USER=testuser
         - MYSQL_PASSWORD=testuserpass
